DO $$
DECLARE
    fk_record RECORD;
BEGIN
    -- Legacy schema used UUID ids. Keep it temporarily in a side column and
    -- introduce numeric id as the canonical primary key.
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'stubs'
          AND column_name = 'id'
          AND data_type = 'uuid'
    ) THEN
        -- Drop foreign keys that currently reference stubs(id) so PK can be replaced.
        FOR fk_record IN
            SELECT
                c.conname AS constraint_name,
                n.nspname AS schema_name,
                cls.relname AS table_name
            FROM pg_constraint AS c
            JOIN pg_class AS cls ON cls.oid = c.conrelid
            JOIN pg_namespace AS n ON n.oid = cls.relnamespace
            WHERE c.contype = 'f'
              AND c.confrelid = 'stubs'::regclass
        LOOP
            EXECUTE format(
                'ALTER TABLE %I.%I DROP CONSTRAINT IF EXISTS %I',
                fk_record.schema_name,
                fk_record.table_name,
                fk_record.constraint_name
            );
        END LOOP;

        ALTER TABLE stubs DROP CONSTRAINT IF EXISTS stubs_pkey;
        ALTER TABLE stubs RENAME COLUMN id TO legacy_uuid_id;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'stubs'
          AND column_name = 'id'
    ) THEN
        ALTER TABLE stubs ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;
    END IF;

    -- Fill missing numeric ids for rows migrated from UUID schema.
    UPDATE stubs SET id = DEFAULT WHERE id IS NULL;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE table_schema = 'public'
          AND table_name = 'stubs'
          AND constraint_name = 'stubs_pkey'
          AND constraint_type = 'PRIMARY KEY'
    ) THEN
        ALTER TABLE stubs ALTER COLUMN id SET NOT NULL;
        ALTER TABLE stubs ADD CONSTRAINT stubs_pkey PRIMARY KEY (id);
    END IF;
END $$;
